export enum TypesColors {
  normal = "bg-slate-300 text-gray-hard",
  fighting = "bg-red-600",
  flying = "bg-cyan-200 text-gray-hard",
  poison = "bg-green-500",
  ground = "bg-yellow-800",
  rock = "bg-amber-500",
  bug = "bg-red-400",
  ghost = "bg-stone-400",
  steel = "bg-sky-900",
  fire = "bg-orange-600",
  water = "bg-blue-600",
  grass = "bg-green-800",
  electric = "bg-cyan-400 text-gray-hard",
  psychic = "bg-red-700",
  ice = "bg-sky-400 text-gray-hard",
  dragon = "bg-red-900",
  dark = "bg-stone-700",
  fairy = "bg-fuchsia-600",
  unknown = "bg-gray-400",
  shadow = "bg-slate-800",
}
